#!/usr/bin/ruby -wKU

task :default => :run

task :run do
  require './lib/hello'
end

require 'greeter'

# Default is World
name = ARGV.first || "World"

greeter = Greeter.new(name)
puts greeter.greet